#erro de proposito depois feito o acerto comentando e tirando a identação com comentário
message = "\nHello Python world!"
#    print(message)
print(message)
